FROM python:3.12

LABEL maintainer "aamirazhar327@gmail.com"

WORKDIR /code

RUN apt-get update && apt-get install -y \
    build-essential \
    protobuf-compiler \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY . /code/

RUN poetry config virtualenvs.create false

RUN poetry install --no-interaction --no-root

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]

